// Cron endpoint — tạo bài blog tự động từ pulse hiện tại
// Được gọi bởi Vercel Cron mỗi giờ

import { NextResponse } from "next/server";
import { createPost } from "@/lib/blog-store";
import { getLatestPulse } from "@/lib/blog-helpers";

export const dynamic = "force-dynamic";
export const maxDuration = 60; // giây

export async function GET(request: Request) {
  // Auth — CHỈ chấp nhận Bearer TNV_SECRET_KEY.
  // (Đã bỏ nhánh x-vercel-cron: header đó client nào cũng gửi được → auth bypass)
  const expected = process.env.TNV_SECRET_KEY;
  const authHeader = request.headers.get("authorization");

  if (!expected) {
    return NextResponse.json(
      { success: false, error: "Server auth not configured" },
      { status: 500 }
    );
  }
  if (authHeader !== `Bearer ${expected}`) {
    return NextResponse.json(
      { success: false, error: "Unauthorized" },
      { status: 401 }
    );
  }

  try {
    const pulse = await getLatestPulse();

    // Gate: không có pulse tươi (Redis hết TTL) thì KHÔNG đăng bài — tránh
    // tự đăng bài rác "Giá $0.00, NEUTRAL" lên blog công khai (TTL 90 ngày).
    if (!pulse || pulse.price <= 0) {
      return NextResponse.json({
        success: true,
        skipped: "no-fresh-pulse",
        message: "Pulse trống hoặc hết hạn — bỏ qua lần này, đợi bot ghi lại",
      });
    }

    const now = new Date();
    const slug = `xau-pulse-${now.toISOString().slice(0, 13).replace(/[-:T]/g, "")}`; // YYYYMMDDHH

    const biasVi = pulse?.bias === "LONG" ? "TĂNG" : pulse?.bias === "SHORT" ? "GIẢM" : "TRUNG TÍNH";
    const biasEn = pulse?.bias || "NEUTRAL";

    const post = {
      slug,
      title: {
        vi: `XAUUSD Pulse — ${now.toLocaleString("vi-VN", { timeZone: "Asia/Ho_Chi_Minh" })}`,
        en: `XAUUSD Pulse — ${now.toISOString()}`,
      },
      excerpt: {
        vi: `Cập nhật nhanh: Giá $${pulse?.price?.toFixed(2) || "—"}, bias ${biasVi}, score ${pulse?.score ?? "—"}/10.`,
        en: `Quick update: Price $${pulse?.price?.toFixed(2) || "—"}, bias ${biasEn}, score ${pulse?.score ?? "—"}/10.`,
      },
      contentMd: {
        vi: `## XAUUSD Pulse ${now.toLocaleString("vi-VN", { timeZone: "Asia/Ho_Chi_Minh" })}

### Tổng quan

- **Giá hiện tại:** $${pulse?.price?.toFixed(2) || "—"}
- **Bias:** ${biasVi}
- **Score:** ${pulse?.score ?? "—"}/10
- **Volatility:** ${pulse?.volatility?.toFixed(2) || "—"}

### Multi-Timeframe

| TF | Bias | Score |
|----|------|-------|
| M15 | ${pulse?.multiTf?.m15?.bias || "—"} | ${pulse?.multiTf?.m15?.score ?? "—"} |
| M30 | ${pulse?.multiTf?.m30?.bias || "—"} | ${pulse?.multiTf?.m30?.score ?? "—"} |
| H1 | ${pulse?.multiTf?.h1?.bias || "—"} | ${pulse?.multiTf?.h1?.score ?? "—"} |

> ⚠️ *Bài tự động từ TNV Gold AI. Quản lý vốn chặt chẽ.*`,
        en: `## XAUUSD Pulse ${now.toISOString()}

### Overview

- **Current price:** $${pulse?.price?.toFixed(2) || "—"}
- **Bias:** ${biasEn}
- **Score:** ${pulse?.score ?? "—"}/10
- **Volatility:** ${pulse?.volatility?.toFixed(2) || "—"}

### Multi-Timeframe

| TF | Bias | Score |
|----|------|-------|
| M15 | ${pulse?.multiTf?.m15?.bias || "—"} | ${pulse?.multiTf?.m15?.score ?? "—"} |
| M30 | ${pulse?.multiTf?.m30?.bias || "—"} | ${pulse?.multiTf?.m30?.score ?? "—"} |
| H1 | ${pulse?.multiTf?.h1?.bias || "—"} | ${pulse?.multiTf?.h1?.score ?? "—"} |

> ⚠️ *Auto-generated by TNV Gold AI. Manage risk carefully.*`,
      },
      tags: ["pulse", "hourly"],
      type: "analysis" as const,
      author: "TNV AI",
      publishedAt: now.getTime(),
      lang: "vi" as const,
      relatedSnapshot: pulse
        ? {
            symbol: pulse.symbol || "XAUUSD",
            price: pulse.price,
            bias: pulse.bias,
            score: pulse.score,
          }
        : undefined,
    };

    await createPost(post);

    return NextResponse.json({
      success: true,
      message: "Post created",
      slug: post.slug,
      title: post.title.vi,
    });
  } catch (err) {
    console.error("[blog-generate] error:", err);
    return NextResponse.json(
      { success: false, error: "Failed to create post" },
      { status: 500 }
    );
  }
}
